Repository prgrms-fe-devcourse/NFE1_2_2_MUX, pull requests merged in 2024-10, with the labels that each got.

#61 [feat] 비밀번호 변경 기능 구현
  src/App.jsx
  src/auth/Dashboard.jsx
  src/auth/Login.jsx
  src/components/modals/ProfileEditModal.jsx
  src/components/modals/UpdatePasswordModal.jsx
  src/utils/api.js
Labels: 🛠️Feat

#56 [feat]: 포스트 작성 기능 구현
  package-lock.json
  package.json
  src/assets/icons/play-button.png
  src/assets/icons/stop-button.png
  src/assets/icons/youtube-music-icon.png
  src/components/modals/PostUpload.jsx
  src/components/modals/TrackUpload.jsx
  src/components/modals/UploadModal.jsx
  src/utils/api.js
  vite.config.js
Labels: 🛠️Feat

#66 [feat] 회원가입 시 보안 수준 규칙 적용
  src/auth/Signup.jsx
Labels: 🛠️Feat

#64 [feat]: CurationCard 더미 데이터로 구현
  src/auth/Dashboard.jsx
  src/components/CurationCard.jsx
Labels: 🛠️Feat

#70 [feat]: 추천포스트 피드 페이지 구현
  src/App.jsx
  src/auth/Dashboard.jsx
  src/components/PostCard.jsx
  src/components/main/Navigation.jsx
  src/pages/PostFeed/PostFeed.jsx
  src/utils/api.js
Labels: 🛠️Feat

#76 [feat]: 네비게이션바 프로필 사진 반영
  src/assets/images/Logo.png
  src/components/main/Navigation.jsx
Labels: 🛠️Feat

#78 [feat] 프로필 페이지 구현
  src/App.jsx
  src/components/UserCard.jsx
  src/components/UserProfile.jsx
  src/components/main/Navigation.jsx
  src/profile/ProfilePage.jsx
  src/utils/api.js
Labels: 🛠️Feat

#80 [feat]: 음원 업로드 기능 구현
  .gitignore
  package-lock.json
  package.json
  src/assets/icons/image-change.png
  src/assets/icons/stop-button.png
  src/assets/images/default-album.png
  src/components/modals/TrackUpload.jsx
  src/utils/api.js
  src/utils/s3.js
Labels: 🛠️Feat

#79 [Feat]: 추천 포스트 상세 모달 구현
  src/assets/icons/Next-Btn.png
  src/assets/icons/Previous-Btn.png
  src/assets/icons/play-button-2.png
  src/assets/icons/stop-button-2.png
  src/assets/icons/trash-button.png
  src/auth/Dashboard.jsx
  src/components/PostCard.jsx
  src/components/modals/PostDetailModal.jsx
  src/pages/PostFeed/PostFeed.jsx
  src/utils/api.js
Labels: 🛠️Feat

#82 [fix]: 정보수정 모달 정상화
  src/profile/ProfilePage.jsx
Labels: 🐛Fix

#87 [fix] fullName 파싱 오류 해결
  src/components/UserProfile.jsx
  src/components/modals/NotificationModal.jsx
Labels: 🐛Fix

#86 [Feat]: PostCard에서 음악을 재생/일시정지 하도록 변경
  src/components/PostCard.jsx
  src/pages/PostFeed/PostFeed.jsx
Labels: 🛠️Feat

#88 [fix] UserCard, UserProfile 파싱오류 해결
  src/components/UserCard.jsx
  src/components/UserProfile.jsx
Labels: 🐛Fix

#91 [Feat] PostCard에서 모달창 열리게 기능 수정
  src/components/PostCard.jsx
  src/pages/PostFeed/PostFeed.jsx
Labels: 🛠️Feat

#92 [feat] 랜딩페이지구현
  src/assets/images/Chat (7).png
  src/assets/images/KakaoTalk_Image_2024-09-28-19-59-52.png
  src/assets/images/adult-3086307_1280.jpg
  src/assets/images/guitar-3943201_1280.jpg
  src/assets/images/image 1.png
  src/assets/images/image 2.png
  src/assets/images/image 3.png
  src/assets/images/image 4.png
  src/assets/images/landing-play.png
  src/assets/images/musician-349790_1280.jpg
  src/pages/LandingPage/LandingPage.jsx
Labels: 🛠️Feat

#93 [feat]: CurationCard 컴포넌트에 API 연결 기능 구현
  src/components/CurationCard.jsx
Labels: 🛠️Feat

#95 [Feat]: PostCard 기능 수정
  src/components/CurationCard.jsx
  src/components/PostCard.jsx
  src/components/ReactionCount.jsx
  src/components/modals/PostDetailModal.jsx
  src/utils/api.js
Labels: 🛠️Feat

#97 [feat]: ArtistCard 컴포넌트에 API 연결 기능 구현
  src/components/ArtistCard.jsx
Labels: 🛠️Feat

#98 [Feat] 프로필 카드 기능 누락 부분 수정
  src/components/CurationCard.jsx
  src/components/PostCard.jsx
  src/components/modals/ArtistTrackDetailModal.jsx
Labels: 🛠️Feat

#99 [Fix] 최종 포스트카드 디자인과 다른 기능 재적용
  src/components/PostCard.jsx
Labels: 🐛Fix

#100 [feat] 실시간 알림 모달 구현
  src/App.jsx
  src/components/main/Navigation.jsx
  src/components/modals/NotificationModal.jsx
  src/components/modals/PostDetailModal.jsx
  src/utils/api.js
Labels: 🛠️Feat

#101 [feat]: curation-artist 페이지 구현
  src/App.jsx
  src/components/ArtistCard.jsx
  src/components/CurationCard.jsx
  src/components/modals/PostUpload.jsx
  src/components/modals/TrackUpload.jsx
  src/components/modals/UploadModal.jsx
  src/pages/Curation-Artist/CurationArt.jsx
Labels: 🛠️Feat

#103 [Feat] 아티스트 음원 상세 모달 구현
  src/components/ArtistCard.jsx
  src/components/modals/ArtistTrackDetailModal.jsx
  src/pages/Curation-Artist/CurationArt.jsx
Labels: 🛠️Feat

#107 [feat] 네비게이션의 알림 아이콘에 도트 표시
  src/components/main/Navigation.jsx
  src/components/modals/NotificationModal.jsx
  src/profile/ProfilePage.jsx
Labels: 🛠️Feat

#110 [feat]: 아티스트 카드 단일 컴포넌트로 기능 구현
  src/components/ArtistCard.jsx
  src/pages/Curation-Artist/CurationArt.jsx
Labels: 🛠️Feat, ♻️Refactor

#116 [Feat] 포스트 & 아티스트 음원 상세 모달 수정 및 반응형 구현
  src/components/modals/ArtistTrackDetailModal.jsx
  src/components/modals/PostDetailModal.jsx
  src/pages/PostFeed/PostFeed.jsx
Labels: 🛠️Feat

#119 [Feat] 가로형 컴포넌트 구현 및 프로필 페이지에 설정
  src/auth/Dashboard.jsx
  src/components/HorizontalArtistCard.jsx
  src/profile/ProfilePage.jsx
Labels: 🛠️Feat

#120 [feat]: 라우터 설정
  src/App.jsx
  src/auth/Login.jsx
  src/components/main/Navigation.jsx
  src/profile/ProfilePage.jsx
Labels: 🛠️Feat

#126 [Refactor] 아티스트 카드 이미지 부분 수정 및 페이지 글귀 수정
  src/components/ArtistCard.jsx
  src/pages/Curation-Artist/CurationArt.jsx
Labels: ♻️Refactor

#127 [fix] 마이페이지 수정
  src/profile/ProfilePage.jsx
Labels: 🐛Fix

#129 [feat] 로그인 실패 문구 표시
  src/auth/Login.jsx
  src/profile/ProfilePage.jsx
Labels: 🛠️Feat

#131 [feat]: 프로필페이지에서 게시글 삭제 가능하도록 기능 구현
  src/components/HorizontalArtistCard.jsx
  src/profile/ProfilePage.jsx
Labels: 🛠️Feat

#134 [fix] 마이페이지 회원정보수정 모달 버그 수정
  src/assets/images/default-profile.png
  src/components/modals/ProfileEditModal.jsx
Labels: 🐛Fix

#135 [Refactor] LandingPage CSS 수정
  src/assets/images/adult-3086307_1280.jpg
  src/assets/images/girl-2.jpg
  src/assets/images/girl-3.jpg
  src/assets/images/girl.jpg
  src/assets/images/guitar-3943201_1280.jpg
  src/assets/images/ipod.png
  src/assets/images/logo-2.png
  src/assets/images/musician-349790_1280.jpg
  src/assets/images/ocean.jpg
  src/assets/images/smile.jpg
  src/assets/images/trees.jpg
  src/pages/LandingPage/LandingPage.jsx
Labels: ♻️Refactor

#137 [style] 메인페이지, C&A페이지 스타일 통합
  src/pages/Curation-Artist/CurationArt.jsx
  src/pages/Main/MainPage.jsx
Labels: 🌈Style

#138 [fix] 화면 커지면 여백이 생기는 문제 해결
  src/pages/Main/MainPage.jsx
Labels: 🐛Fix

#139 [feat]: 플레이어 재생바 구현
  src/App.jsx
  src/assets/icons/Next.png
  src/assets/icons/Pause.png
  src/assets/icons/Play.png
  src/assets/icons/Playlist.png
  src/assets/icons/Prev.png
  src/components/ArtistCard.jsx
  src/components/CurationCard.jsx
  src/components/PostCard.jsx
  src/components/main/MusicPlayer.jsx
  src/components/modals/ArtistTrackDetailModal.jsx
  src/components/modals/PostDetailModal.jsx
  src/pages/Curation-Artist/CurationArt.jsx
  src/pages/PostFeed/PostFeed.jsx
Labels: 🛠️Feat, 💥Conflict

#140 [feat]: 검색 결과 페이지 구현
  src/App.jsx
  src/components/UserCard.jsx
  src/components/main/MainPage.jsx
  src/components/main/Navigation.jsx
  src/pages/Main/MainPage.jsx
  src/pages/Search/ResultsList.jsx
  src/pages/Search/SearchPage.jsx
  src/utils/api.js
Labels: 🛠️Feat

#141 [fix] 메인페이지 추천포스트 섹션 수정, 네비게이션 수정
  src/components/main/Navigation.jsx
Labels: 🐛Fix

#142 #136[fix]: 큐레이션 카드 키값 살림
  src/components/CurationCard.jsx
Labels: 🐛Fix
